//! The CH32X035's remap tables: which pin each timer channel and each
//! USART's transmitter reaches, by the remap value AFIO's `PCFR1` holds.
//! Generated by `scripts/x035_pins.py` from ch32-metapac 0.1.1's
//! `metadata_0036.rs` (ch32-data), never typed, and numbered 24 to a
//! port: PB0 is 24 and PC0 48.
//! `NONE` is a signal that remap does not bring out.

/// A signal a remap does not bring out to any pin.
pub const NONE: u8 = u8::MAX;

/// A timer's four channels and three complements.
pub type TimerPins = ([u8; 4], [u8; 3]);

/// TIM1's CH1..CH4 and CH1N..CH3N, by its remap value.
pub const TIM1: &[TimerPins] = &[
    ([33, 34, 35, 64], [30, 31, 32]),
    ([33, 34, 35, 64], [7, 24, 25]),
    ([33, 34, 35, 36], [30, 31, 32]),
    ([48, 49, 50, 51], [53, 54, 55]),
];

/// TIM2's CH1..CH4 and CH1N..CH3N, by its remap value.
pub const TIM2: &[TimerPins] = &[
    ([0, 1, 2, 3], [21, 22, 23]),
    ([45, 39, 2, 3], [12, 13, 14]),
    ([0, 1, 27, 28], [51, 22, 23]),
    ([45, 39, 27, 28], [12, 13, 14]),
    ([40, 41, 42, 43], [49, 50, 51]),
    ([67, 12, 13, 48], [66, 36, 27]),
    ([67, 62, 63, 48], [35, 36, 27]),
];

/// TIM3's CH1..CH4 and CH1N..CH3N, by its remap value.
pub const TIM3: &[TimerPins] = &[
    ([6, 7, NONE, NONE], [NONE, NONE, NONE]),
    ([28, 29, NONE, NONE], [NONE, NONE, NONE]),
    ([67, 66, NONE, NONE], [NONE, NONE, NONE]),
    ([3, 4, NONE, NONE], [NONE, NONE, NONE]),
];

/// USART1's TX pin, by its remap value.
pub const USART1_TX: &[u8] = &[34, 10, 34, 7];

/// USART2's TX pin, by its remap value.
pub const USART2_TX: &[u8] = &[2, 20, 15, 48, 15];

/// USART3's TX pin, by its remap value.
pub const USART3_TX: &[u8] = &[27, 66, 18];

/// USART4's TX pin, by its remap value.
pub const USART4_TX: &[u8] = &[24, 5, 64, 33, 37, 65];
