/// Median of 5 samples, for samples taken at 1000 Hz.
///
/// Delays everything by 2 samples, 2 ms at that rate, and takes a spike
/// narrower than half the window out without a trace. Generated by rusty: `f32`
/// throughout, no `std` and no allocation.
pub struct Despike {
    /// The last 5 inputs, each written over the oldest.
    window: [f32; 5],
    /// Where the next input goes, which is where the oldest is.
    next: usize,
}

impl Despike {
    pub const fn new() -> Self {
        Self {
            window: [0.0; 5],
            next: 0,
        }
    }

    /// One sample in, the median of the last 5 out.
    pub fn step(&mut self, x: f32) -> f32 {
        self.window[self.next] = x;
        self.next += 1;
        if self.next == 5 {
            self.next = 0;
        }
        let mut sorted = self.window;
        sorted.sort_unstable_by(f32::total_cmp);
        sorted[2]
    }
}

impl Default for Despike {
    fn default() -> Self {
        Self::new()
    }
}
