/// Butterworth low-pass of order 3 at 50 Hz, for samples taken at 1000 Hz.
///
/// The coefficients are right at that rate and no other: run `step` at another
/// and every frequency above moves with it. Generated by rusty: 2 sections in
/// Direct Form II Transposed, `f32` throughout, no `std` and no allocation.
pub struct LowPass {
    /// Each section's two delays.
    state: [[f32; 2]; 2],
}

impl LowPass {
    /// `[b0, b1, b2, a1, a2]` for each section, `a0` divided out.
    // A coefficient can come within a few digits of pi or 1/sqrt(2) by
    // arithmetic, and clippy would take it for the constant.
    #[allow(clippy::approx_constant)]
    #[rustfmt::skip]
    const SECTIONS: [[f32; 5]; 2] = [
        [0.13672873, 0.13672873, 0.0, -0.72654253, 0.0],
        [0.021196675, 0.04239335, 0.021196675, -1.6475523, 0.7323389],
    ];

    pub const fn new() -> Self {
        Self {
            state: [[0.0; 2]; 2],
        }
    }

    /// One sample in, one filtered sample out.
    pub fn step(&mut self, x: f32) -> f32 {
        let mut y = x;
        for (section, delay) in Self::SECTIONS.iter().zip(self.state.iter_mut()) {
            let out = section[0] * y + delay[0];
            delay[0] = section[1] * y - section[3] * out + delay[1];
            delay[1] = section[2] * y - section[4] * out;
            y = out;
        }
        y
    }
}

impl Default for LowPass {
    fn default() -> Self {
        Self::new()
    }
}
