/// Windowed-sinc low-pass at 100 Hz, 31 taps through a Hann window, for samples
/// taken at 1000 Hz.
///
/// Delays everything by 15 samples, 15 ms at that rate. The taps are right at
/// that rate and no other. Generated by rusty: 31 taps, `f32` throughout, no
/// `std` and no allocation.
pub struct Smooth {
    /// The last 31 inputs, each written over the oldest.
    history: [f32; 31],
    /// Where the next input goes, which is where the oldest is.
    next: usize,
}

impl Smooth {
    /// The response to a single sample: the first tap meets the newest.
    // A tap can come within a few digits of pi or 1/sqrt(2) by arithmetic,
    // and clippy would take it for the constant.
    #[allow(clippy::approx_constant)]
    #[rustfmt::skip]
    const TAPS: [f32; 31] = [
        0.0, 0.00051017886, 0.0019682106, 0.0037056531, 0.00379105,
        0.0, -0.008391772, -0.018977838, -0.025920263, -0.02162323,
        0.0, 0.040045135, 0.09268621, 0.14604428, 0.18586022,
        0.20060429, 0.18586022, 0.14604428, 0.09268621, 0.040045135,
        0.0, -0.02162323, -0.025920263, -0.018977838, -0.008391772,
        0.0, 0.00379105, 0.0037056531, 0.0019682106, 0.00051017886,
        0.0,
    ];

    pub const fn new() -> Self {
        Self {
            history: [0.0; 31],
            next: 0,
        }
    }

    /// One sample in, one filtered sample out.
    pub fn step(&mut self, x: f32) -> f32 {
        self.history[self.next] = x;
        self.next += 1;
        if self.next == 31 {
            self.next = 0;
        }
        // Oldest first: from `next` to the end, then from the start.
        let (newer, older) = self.history.split_at(self.next);
        let mut y = 0.0;
        for (tap, sample) in Self::TAPS.iter().rev().zip(older.iter().chain(newer)) {
            y += tap * sample;
        }
        y
    }
}

impl Default for Smooth {
    fn default() -> Self {
        Self::new()
    }
}
