//! Compiles `data/templates/` in: every directory with a `template.toml`
//! becomes a [`Template`] the playground and the wizard write out, and the
//! ones that say `playground = <n>` become the playground list, in that
//! order. Adding a template is adding a directory; no code names it.
//!
//! Two files in `OUT_DIR`: `templates.rs` (the files, through
//! `include_str!`, for the backend) and `playgrounds.rs` (the list, which
//! the wasm model reads too, since the window offers the same list).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

struct Found {
    name: String,
    chip: Option<String>,
    playground: Option<i64>,
    files: Vec<(String, PathBuf)>,
}

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("data")
        .join("templates");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut dirs: Vec<PathBuf> = std::fs::read_dir(&root)
        .unwrap_or_else(|e| panic!("{}: {e}", root.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.join("template.toml").is_file())
        .collect();
    dirs.sort();

    let mut found = Vec::new();
    for dir in dirs {
        let manifest = dir.join("template.toml");
        println!("cargo:rerun-if-changed={}", manifest.display());
        let text = std::fs::read_to_string(&manifest).expect("a readable template.toml");
        let table: toml::Table = text
            .parse()
            .unwrap_or_else(|e| panic!("{}: {e}", manifest.display()));
        for key in table.keys() {
            assert!(
                ["chip", "playground", "file"].contains(&key.as_str()),
                "{}: `{key}` is not a template key",
                manifest.display()
            );
        }
        let name = dir.file_name().unwrap().to_string_lossy().into_owned();
        let files = table
            .get("file")
            .and_then(|f| f.as_array())
            .unwrap_or_else(|| panic!("{}: no [[file]]", manifest.display()))
            .iter()
            .map(|file| {
                let field = |key: &str| {
                    file.get(key)
                        .and_then(|v| v.as_str())
                        .unwrap_or_else(|| {
                            panic!("{}: a [[file]] without `{key}`", manifest.display())
                        })
                        .to_string()
                };
                let source = dir.join(field("from"));
                let source = source.canonicalize().unwrap_or_else(|e| {
                    panic!("{}: {}: {e}", manifest.display(), source.display())
                });
                println!("cargo:rerun-if-changed={}", source.display());
                (field("path"), source)
            })
            .collect();
        found.push(Found {
            name,
            chip: table
                .get("chip")
                .and_then(|c| c.as_str())
                .map(str::to_string),
            playground: table.get("playground").and_then(|p| p.as_integer()),
            files,
        });
    }

    let mut templates = String::from(
        "// Generated by build.rs from data/templates/*/template.toml.\n\
         pub(crate) const TEMPLATES: &[Template] = &[\n",
    );
    for template in &found {
        let chip = match &template.chip {
            Some(chip) => format!("Some({chip:?})"),
            None => "None".to_string(),
        };
        writeln!(
            templates,
            "    Template {{\n        name: {:?},\n        chip: {chip},\n        files: &[",
            template.name
        )
        .unwrap();
        for (path, source) in &template.files {
            // A raw string with enough hashes for any path.
            writeln!(
                templates,
                "            ({path:?}, include_str!(r##\"{}\"##)),",
                source.display()
            )
            .unwrap();
        }
        templates.push_str("        ],\n    },\n");
    }
    templates.push_str("];\n");

    let mut offered: Vec<(i64, &str)> = found
        .iter()
        .filter_map(|t| Some((t.playground?, t.name.as_str())))
        .collect();
    offered.sort();
    for pair in offered.windows(2) {
        assert!(
            pair[0].0 != pair[1].0,
            "templates {} and {} both say playground = {}",
            pair[0].1,
            pair[1].1,
            pair[0].0
        );
    }
    let names: Vec<String> = offered
        .iter()
        .map(|(_, name)| format!("{name:?}"))
        .collect();
    let playgrounds = format!(
        "// Generated by build.rs from data/templates/*/template.toml.\n\
         /// The playgrounds, in the order they are offered.\n\
         pub const PLAYGROUNDS: [&str; {}] = [{}];\n",
        names.len(),
        names.join(", ")
    );

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out.join("templates.rs"), templates).unwrap();
    std::fs::write(out.join("playgrounds.rs"), playgrounds).unwrap();
}
