"""Generate rusty-mcu's CH32X035 remap tables from ch32-metapac's metadata.

    python crates/rusty-mcu/scripts/x035_pins.py         ~/.cargo/registry/src/*/ch32-metapac-0.1.1/src/chips/metadata_0036.rs         crates/rusty-mcu/src/ch32/x035_pins.rs

Pins are numbered 24 to a port (PA0 0, PB0 24, PC0 48), the width of the
part's GPIO registers.
"""
import io
import re
import sys

OUT = io.StringIO()
_print = print


def print(*args, **kw):
    _print(*args, file=OUT, **kw)


text = open(sys.argv[1], encoding="utf-8").read()


def pin_number(name):
    port, n = name[1], int(name[2:])
    return {"A": 0, "B": 24, "C": 48}[port] + n


def pins_of(peripheral):
    start = text.find(f'name: "{peripheral}",\n        address')
    assert start >= 0, peripheral
    end = text.find("Peripheral {", start + 10)
    seg = text[start:end if end > 0 else len(text)]
    table = {}
    for m in re.finditer(
        r'PeripheralPin \{\s*pin: "(\w+)",\s*signal: "(\w+)",\s*remap: (?:Some\((\d+)\)|None)', seg
    ):
        pin, signal, remap = m.group(1), m.group(2), int(m.group(3) or 0)
        table.setdefault(remap, {})[signal] = pin_number(pin)
    return table


def timer(name, complements):
    table = pins_of(name)
    rows = []
    for remap in range(max(table) + 1):
        signals = table.get(remap, {})
        main = ", ".join(f"{signals.get(f'CH{c}', 'NONE')}" for c in range(1, 5))
        comp = ", ".join(f"{signals.get(f'CH{c}N', 'NONE')}" for c in range(1, 4))
        rows.append(f"    ([{main}], [{comp}]),")
    kind = "TimerPins"
    print(f"/// {name}'s CH1..CH4 and CH1N..CH3N, by its remap value.")
    print(f"pub const {name}: &[{kind}] = &[")
    print("\n".join(rows))
    print("];\n")


def usart(name):
    table = pins_of(name)
    pins = ", ".join(f"{table.get(r, {}).get('TX', 'NONE')}" for r in range(max(table) + 1))
    print(f"/// {name}'s TX pin, by its remap value.")
    print(f"pub const {name}_TX: &[u8] = &[{pins}];\n")


print("//! The CH32X035's remap tables: which pin each timer channel and each")
print("//! USART's transmitter reaches, by the remap value AFIO's `PCFR1` holds.")
print("//! Generated by `scripts/x035_pins.py` from ch32-metapac 0.1.1's")
print("//! `metadata_0036.rs` (ch32-data), never typed, and numbered 24 to a")
print("//! port: PB0 is 24 and PC0 48.")
print("//! `NONE` is a signal that remap does not bring out.")
print()
print("/// A signal a remap does not bring out to any pin.")
print("pub const NONE: u8 = u8::MAX;")
print()
print("/// A timer's four channels and three complements.")
print("pub type TimerPins = ([u8; 4], [u8; 3]);")
print()
timer("TIM1", True)
timer("TIM2", True)
timer("TIM3", False)
for n in range(1, 5):
    usart(f"USART{n}")

with open(sys.argv[2], "w", encoding="utf-8", newline="") as f:
    f.write(OUT.getvalue().rstrip("\n") + "\n")
