[package]
name = "rusty-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rusty-ai = { path = "../rusty-ai" }
rusty-core = { path = "../rusty-core" }
rusty-edit = { path = "../rusty-edit" }
rusty-embed = { path = "../rusty-embed" }
rusty-ipc = { path = "../rusty-ipc" }
rusty-lsp = { path = "../rusty-lsp" }
rusty-dbg = { path = "../rusty-dbg" }
rusty-term = { path = "../rusty-term" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.2"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
