//! A realised filter as `no_std` Rust for the firmware that runs it: a
//! struct holding the filter's state, its coefficients as constants,
//! `const fn new()` and `fn step(&mut self, x: f32) -> f32`.
//!
//! **In `f32`**, because that is what the parts run: the ESP32's FPU is
//! single precision and the C3 has none, where a double is twice the
//! soft-float work of a float. **In `apply`'s arithmetic and in its
//! order** — Direct Form II Transposed, the taps from the oldest sample to
//! the newest, the window sorted — so the code computes what the design lab
//! drew, to single precision. `single` is that code's arithmetic run here,
//! and an export whose single-precision answer strays from the design by
//! more than [`LIMIT`] is refused rather than written: a low-pass whose
//! gain at DC is 0.3% off is a thermometer that reads 25.08 °C through a
//! filter that was meant not to touch it.
//!
//! **Checked in, compiled and run.** Three exports live in
//! `tests/fixtures/dsp/` and the tests `include!` them, so a generator
//! change that breaks the code breaks the build, one that changes its text
//! is a diff somebody reviews, and each is held both to `single`, bit for
//! bit, and to `apply`. They are also handed to `rustc` in a `#![no_std]`
//! crate with every warning an error, which is where firmware builds them.

use super::design::{Band, BiquadKind, Design, Pass};
use super::filter::{Coefficients, Filter, Section};
use super::refusal::Refusal;
use super::spectrum::Window;
use crate::signal::{Component, Signal};

/// The most an export's `f32` answer may stray from its design, as a share
/// of the output's peak: a tenth of a percent, a few counts of a twelve-bit
/// converter.
///
/// Measured, a Butterworth low-pass of order two or four keeps inside it
/// down to a cutoff of a five-hundredth of the rate, and one of order eight
/// to a two-hundredth; below that the gain at DC is set by digits `f32`
/// does not have, and the answer is to filter at a lower rate.
pub const LIMIT: f64 = 1e-3;

impl Filter {
    /// This filter as `no_std` Rust, its struct called `name` — or why not:
    /// a name a struct cannot have ([`check_name`]), or a filter that
    /// single precision cannot follow ([`LIMIT`]).
    pub fn code(&self, name: &str) -> Result<String, Refusal> {
        check_name(name)?;
        let error = self.precision();
        if error.is_nan() || error > LIMIT {
            return Err(Refusal::Precision {
                error,
                limit: LIMIT,
            });
        }
        let heading = format!(
            "{}, for samples taken at {} Hz.",
            about(&self.design),
            self.rate
        );
        let made = "`f32` throughout, no `std` and no allocation.";
        Ok(match &self.coefficients {
            Coefficients::Sections(sections) => {
                let count = sections.len();
                let plural = if count == 1 { "" } else { "s" };
                let doc = doc(&[
                    heading,
                    format!(
                        "The coefficients are right at that rate and no other: run `step` \
                         at another and every frequency above moves with it. Generated by \
                         rusty: {count} section{plural} in Direct Form II Transposed, {made}"
                    ),
                ]);
                let rows: String = sections
                    .iter()
                    .map(|s| {
                        let row = [s.b[0], s.b[1], s.b[2], s.a[0], s.a[1]].map(literal);
                        format!("        [{}],\n", row.join(", "))
                    })
                    .collect();
                fill(
                    RECURSIVE,
                    &[
                        ("{doc}", &doc),
                        ("{name}", name),
                        ("{count}", &count.to_string()),
                        ("{rows}", &rows),
                    ],
                )
            }
            Coefficients::Taps(taps) => {
                let count = taps.len();
                let doc = doc(&[
                    heading,
                    format!(
                        "Delays everything by {}. The taps are right at that rate and no \
                         other. Generated by rusty: {count} taps, {made}",
                        self.delay(count)
                    ),
                ]);
                let rows: String = taps
                    .chunks(5)
                    .map(|line| {
                        let line: Vec<String> = line.iter().copied().map(literal).collect();
                        format!("        {},\n", line.join(", "))
                    })
                    .collect();
                fill(
                    FINITE,
                    &[
                        ("{doc}", &doc),
                        ("{name}", name),
                        ("{count}", &count.to_string()),
                        ("{rows}", &rows),
                    ],
                )
            }
            Coefficients::Median(taps) => {
                let doc = doc(&[
                    heading,
                    format!(
                        "Delays everything by {}, and takes a spike narrower than half the \
                         window out without a trace. Generated by rusty: {made}",
                        self.delay(*taps)
                    ),
                ]);
                let half = taps / 2;
                let middle = if taps % 2 == 1 {
                    format!("sorted[{half}]")
                } else {
                    format!("(sorted[{}] + sorted[{half}]) / 2.0", half - 1)
                };
                fill(
                    MEDIAN,
                    &[
                        ("{doc}", &doc),
                        ("{name}", name),
                        ("{count}", &taps.to_string()),
                        ("{middle}", &middle),
                    ],
                )
            }
        })
    }

    /// Half a window of `taps` samples late, in samples and in time: the
    /// delay of a symmetric FIR and of a median alike.
    fn delay(&self, taps: usize) -> String {
        let samples = (taps - 1) as f64 / 2.0;
        let millis = samples / self.rate * 1000.0;
        format!("{samples} samples, {} ms at that rate", short(millis))
    }

    /// How far the `f32` arithmetic the export runs strays from `apply`,
    /// as a share of the output's peak, over a probe of an offset and
    /// white noise: the offset finds a wrong gain at DC, the noise every
    /// frequency, and the probe lasts twenty of the slowest pole's time
    /// constants so a slow drift has the time to show.
    fn precision(&self) -> f64 {
        let probe = Signal {
            components: vec![Component::Dc { level: 1.0 }, Component::White { rms: 1.0 }],
        }
        .render(self.rate, probe_length(&self.coefficients), 0);
        let exact = self.apply(&probe);
        let input: Vec<f32> = probe.iter().map(|&x| x as f32).collect();
        let single = single(&self.coefficients, &input);
        let peak = exact.iter().fold(0.0f64, |most, v| most.max(v.abs()));
        let worst = exact
            .iter()
            .zip(&single)
            .fold(0.0f64, |most, (e, s)| most.max((e - f64::from(*s)).abs()));
        worst / peak
    }
}

/// Whether `name` can name an exported filter's struct: an upper-case
/// ASCII letter, then ASCII letters and digits, and not `Self`. Anything
/// else fails to compile or compiles with a warning — `non_camel_case_types`
/// — that a `-D warnings` build turns into a failure somewhere else. For the
/// frontend to say so beside the field, while it is typed.
pub fn check_name(name: &str) -> Result<(), Refusal> {
    let mut chars = name.chars();
    let first = chars.next().is_some_and(|c| c.is_ascii_uppercase());
    if first && chars.all(|c| c.is_ascii_alphanumeric()) && name != "Self" {
        Ok(())
    } else {
        Err(Refusal::Name {
            name: name.to_string(),
        })
    }
}

/// A coefficient as the export holds it: rounded to `f32`, and a zero of
/// either sign written as the zero it is — a `-0.0` among the taps reads as
/// a number somebody chose, and multiplies to the same nothing.
fn narrow(value: f64) -> f32 {
    let single = value as f32;
    if single == 0.0 { 0.0 } else { single }
}

/// A coefficient as the `f32` literal that reads back to it exactly:
/// `{:?}` is the shortest such, which is also what keeps clippy's
/// `excessive_precision` quiet.
fn literal(value: f64) -> String {
    format!("{:?}", narrow(value))
}

/// A number to four significant figures, without trailing zeros.
fn short(x: f64) -> String {
    let magnitude = if x == 0.0 {
        0
    } else {
        x.abs().log10().floor() as i32
    };
    let places = 3i32.saturating_sub(magnitude).clamp(0, 12) as usize;
    let text = format!("{x:.places$}");
    if text.contains('.') {
        text.trim_end_matches('0').trim_end_matches('.').to_string()
    } else {
        text
    }
}

/// Paragraphs as a doc comment, each wrapped to eighty columns and a
/// bare `///` between them — what a person writing it would have written,
/// whatever length the numbers in it came to.
fn doc(paragraphs: &[String]) -> String {
    const WIDTH: usize = 80;
    let mut out = String::new();
    for (at, paragraph) in paragraphs.iter().enumerate() {
        if at > 0 {
            out.push_str("///\n");
        }
        let mut line = String::from("///");
        for word in paragraph.split_whitespace() {
            if line.len() > 3 && line.len() + 1 + word.len() > WIDTH {
                out.push_str(&line);
                out.push('\n');
                line = String::from("///");
            }
            line.push(' ');
            line.push_str(word);
        }
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// `template` with each placeholder replaced.
fn fill(template: &str, values: &[(&str, &str)]) -> String {
    values
        .iter()
        .fold(template.to_string(), |text, (from, to)| {
            text.replace(from, to)
        })
}

/// What the design is, in the words of the comment above the struct.
fn about(design: &Design) -> String {
    match *design {
        Design::MovingAverage { taps } => format!("Moving average of {taps} samples"),
        Design::Exponential { alpha } => {
            format!("Exponential smoothing, y += {alpha} * (x - y)")
        }
        Design::Biquad { kind, cutoff, q } => {
            let kind = match kind {
                BiquadKind::LowPass => "low-pass",
                BiquadKind::HighPass => "high-pass",
                BiquadKind::BandPass => "band-pass",
                BiquadKind::Notch => "notch",
            };
            format!("Biquad {kind} at {cutoff} Hz, Q {q}")
        }
        Design::Butterworth {
            pass,
            order,
            cutoff,
        } => {
            let pass = match pass {
                Pass::Low => "low",
                Pass::High => "high",
            };
            format!("Butterworth {pass}-pass of order {order} at {cutoff} Hz")
        }
        Design::Fir { band, taps, window } => {
            let band = match band {
                Band::LowPass { cutoff } => format!("low-pass at {cutoff} Hz"),
                Band::HighPass { cutoff } => format!("high-pass at {cutoff} Hz"),
                Band::BandPass { low, high } => format!("band-pass from {low} to {high} Hz"),
            };
            let window = match window {
                Window::Rectangular => "rectangular",
                Window::Hann => "Hann",
                Window::Blackman => "Blackman",
            };
            format!("Windowed-sinc {band}, {taps} taps through a {window} window")
        }
        Design::Median { taps } => format!("Median of {taps} samples"),
    }
}

/// How long a probe has to run: twenty of the slowest pole's time
/// constants, between 2¹² and 2¹⁸ samples.
fn probe_length(coefficients: &Coefficients) -> usize {
    let (shortest, longest) = (1 << 12, 1 << 18);
    let Coefficients::Sections(sections) = coefficients else {
        return shortest;
    };
    let slowest = sections.iter().map(radius).fold(0.0f64, f64::max);
    let settled = 20.0 / (1.0 - slowest).max(1e-9);
    (settled as usize).clamp(shortest, longest)
}

/// The largest magnitude among a section's poles, the roots of
/// `z² + a1·z + a2`.
fn radius(section: &Section) -> f64 {
    let [a1, a2] = section.a;
    let discriminant = a1 * a1 - 4.0 * a2;
    if discriminant < 0.0 {
        a2.sqrt()
    } else {
        let root = discriminant.sqrt();
        (-a1 + root).abs().max((-a1 - root).abs()) / 2.0
    }
}

/// The exported code's arithmetic, run here: the coefficients rounded to
/// `f32` as the literals are, every operation in the order the code writes
/// it, so this is bit for bit what `step` returns — which is what the
/// checked-in exports are held to.
fn single(coefficients: &Coefficients, samples: &[f32]) -> Vec<f32> {
    match coefficients {
        Coefficients::Sections(sections) => {
            let table: Vec<[f32; 5]> = sections
                .iter()
                .map(|s| [s.b[0], s.b[1], s.b[2], s.a[0], s.a[1]].map(narrow))
                .collect();
            let mut state = vec![[0.0f32; 2]; table.len()];
            samples
                .iter()
                .map(|&x| {
                    let mut y = x;
                    for (section, delay) in table.iter().zip(state.iter_mut()) {
                        let out = section[0] * y + delay[0];
                        delay[0] = section[1] * y - section[3] * out + delay[1];
                        delay[1] = section[2] * y - section[4] * out;
                        y = out;
                    }
                    y
                })
                .collect()
        }
        Coefficients::Taps(taps) => {
            let taps: Vec<f32> = taps.iter().copied().map(narrow).collect();
            let mut history = vec![0.0f32; taps.len()];
            let mut next = 0;
            samples
                .iter()
                .map(|&x| {
                    history[next] = x;
                    next += 1;
                    if next == taps.len() {
                        next = 0;
                    }
                    let (newer, older) = history.split_at(next);
                    let mut y = 0.0f32;
                    for (tap, sample) in taps.iter().rev().zip(older.iter().chain(newer)) {
                        y += tap * sample;
                    }
                    y
                })
                .collect()
        }
        Coefficients::Median(taps) => {
            let taps = *taps;
            let mut window = vec![0.0f32; taps];
            let mut next = 0;
            samples
                .iter()
                .map(|&x| {
                    window[next] = x;
                    next += 1;
                    if next == taps {
                        next = 0;
                    }
                    let mut sorted = window.clone();
                    sorted.sort_unstable_by(f32::total_cmp);
                    let half = taps / 2;
                    if taps % 2 == 1 {
                        sorted[half]
                    } else {
                        (sorted[half - 1] + sorted[half]) / 2.0
                    }
                })
                .collect()
        }
    }
}

/// Second-order sections, Direct Form II Transposed.
const RECURSIVE: &str = "\
{doc}pub struct {name} {
    /// Each section's two delays.
    state: [[f32; 2]; {count}],
}

impl {name} {
    /// `[b0, b1, b2, a1, a2]` for each section, `a0` divided out.
    // A coefficient can come within a few digits of pi or 1/sqrt(2) by
    // arithmetic, and clippy would take it for the constant.
    #[allow(clippy::approx_constant)]
    #[rustfmt::skip]
    const SECTIONS: [[f32; 5]; {count}] = [
{rows}    ];

    pub const fn new() -> Self {
        Self {
            state: [[0.0; 2]; {count}],
        }
    }

    /// One sample in, one filtered sample out.
    pub fn step(&mut self, x: f32) -> f32 {
        let mut y = x;
        for (section, delay) in Self::SECTIONS.iter().zip(self.state.iter_mut()) {
            let out = section[0] * y + delay[0];
            delay[0] = section[1] * y - section[3] * out + delay[1];
            delay[1] = section[2] * y - section[4] * out;
            y = out;
        }
        y
    }
}

impl Default for {name} {
    fn default() -> Self {
        Self::new()
    }
}
";

/// Taps over a ring of past inputs.
const FINITE: &str = "\
{doc}pub struct {name} {
    /// The last {count} inputs, each written over the oldest.
    history: [f32; {count}],
    /// Where the next input goes, which is where the oldest is.
    next: usize,
}

impl {name} {
    /// The response to a single sample: the first tap meets the newest.
    // A tap can come within a few digits of pi or 1/sqrt(2) by arithmetic,
    // and clippy would take it for the constant.
    #[allow(clippy::approx_constant)]
    #[rustfmt::skip]
    const TAPS: [f32; {count}] = [
{rows}    ];

    pub const fn new() -> Self {
        Self {
            history: [0.0; {count}],
            next: 0,
        }
    }

    /// One sample in, one filtered sample out.
    pub fn step(&mut self, x: f32) -> f32 {
        self.history[self.next] = x;
        self.next += 1;
        if self.next == {count} {
            self.next = 0;
        }
        // Oldest first: from `next` to the end, then from the start.
        let (newer, older) = self.history.split_at(self.next);
        let mut y = 0.0;
        for (tap, sample) in Self::TAPS.iter().rev().zip(older.iter().chain(newer)) {
            y += tap * sample;
        }
        y
    }
}

impl Default for {name} {
    fn default() -> Self {
        Self::new()
    }
}
";

/// A window sorted per sample.
const MEDIAN: &str = "\
{doc}pub struct {name} {
    /// The last {count} inputs, each written over the oldest.
    window: [f32; {count}],
    /// Where the next input goes, which is where the oldest is.
    next: usize,
}

impl {name} {
    pub const fn new() -> Self {
        Self {
            window: [0.0; {count}],
            next: 0,
        }
    }

    /// One sample in, the median of the last {count} out.
    pub fn step(&mut self, x: f32) -> f32 {
        self.window[self.next] = x;
        self.next += 1;
        if self.next == {count} {
            self.next = 0;
        }
        let mut sorted = self.window;
        sorted.sort_unstable_by(f32::total_cmp);
        {middle}
    }
}

impl Default for {name} {
    fn default() -> Self {
        Self::new()
    }
}
";

#[cfg(test)]
mod tests;
